### PR TITLE
FindTAO cmake module

### PR DESCRIPTION
**Pull request by allo-**

### CODE REVIEW

**Comment by jedbrown** [comment]
I'm sorry about the slow reply. Is this still relevant since TAO became part of PETSc in v3.5 (released last year)?

**Comment by allo-** [comment]
I need to check this, i use this with PETSc 3.4.5 and TAO 2.2.2.

**Comment by jedbrown** [comment]
Yikes, those versions have not been supported in a while.  Please upgrade to PETSc 3.6.

**Comment by allo-** [comment]
This module is not needed anymore with PETSc 3.6

**Pull request closed without merging**
